version: '3'

services:
  authentication:
    container_name: authentication_service
    build:
      context: ./authentication
      dockerfile: ./authentication.dockerfile
    restart: always
    ports:
      - "9000:80"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      X_API_KEY: "sWOmNsF8Ht9lE9wMU9cW7w==n"
    deploy:
      mode: replicated
      replicas: 1
  
  mailer-service:
    container_name: "mail_service"
    build:
      context: ./mail-service
      dockerfile: ./mail-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "Admin"
      FROM_ADDRESS: "admin@example.com"
    ports:
      - "9001:80"

  enrollment:
    container_name: enrollment_service
    build:
      context: ./enrollment
      dockerfile: ./enrollment.dockerfile
    restart: always
    ports:
      - "9002:80"
    environment:
      X_API_KEY: "sWOmNsF8Ht9lE9wMU9cW7w==n"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    container_name: postgresql
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./initdb/users.sql:/docker-entrypoint-initdb.d/users.sql
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    container_name: mongodb
    image: 'mongo:4.4.3'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootroot 
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    container_name: mailhog 
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
  
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: api-gateway.dockerfile
    container_name: api-gateway
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
 