version: '3'

services:
  authentication:
    container_name: authentication_service
    build:
      context: ./authentication
      dockerfile: ./authentication.dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      X_API_KEY: "sWOmNsF8Ht9lE9wMU9cW7w==n"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./db-data/init/users.sql:/docker-entrypoint-initdb.d/users.sql
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: 'mongo:4.4.3'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootroot 
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
 